# ironloggui configuration file
ironloggui:
    # relative Rootdir for searching filename
    rootdir: /..
    # list filename strings for searching. File searcher will search for *name*
    searchfor: 
        - '*IrondemoLog.txt'
    # list explicite files here (absolute Path required)
    explicitfiles:
        - ''

