# ironloggui configuration file
ironloggui:
    # Rootdir for searching filename
    rootdir: ..
    # list filename strings for searching
    searchfor: 
        - irondemoLog.txt
    # list explicite files here
    explicitfiles:


