# ironloggui configuration file
ironloggui:
    # relative Rootdir for searching filename
    rootdir: /../..
    # list filename strings for searching. File searcher will search for *name*
    searchfor: 
        - 'text.txt'
        #- 'test.txt'
    # list explicite files here (absolute Path required)
    explicitfiles:
        - '/home/rohdem/Arbeitsflaeche/test.txt'

